In [1]:
import itertools
import random

import numpy as np

from scipy.spatial.distance import hamming


# Build list of all possible permutations
random.seed(42)
permuts_list = list(itertools.permutations(range(9)))
permuts_array = np.array(permuts_list)
no_permuts = len(permuts_list)


# Take top x permutations which have max average hamming distance

In [2]:
permuts_to_take = 1000
set_of_taken = set()
cnt_iterations = 0
while True:
    cnt_iterations += 1
    x = random.randint(1, no_permuts - 1)
    y = random.randint(1, no_permuts - 1)
    permut_1 = permuts_array[x]
    permut_2 = permuts_array[y]
    hd = hamming(permut_1, permut_2)

    if hd > 0.9 and (not x in set_of_taken) and (not y in set_of_taken):
        set_of_taken.add(x)
        set_of_taken.add(y)

        if len(set_of_taken) == permuts_to_take:
            break

    if cnt_iterations % 100 == 0:
        print ("Already performed count of iterations with pairs of jigsaw permutations", cnt_iterations)
        print ("Length of set of taken: ",len(set_of_taken))

print ("No of iterations it took to build top - {} permutations array = {}".format(permuts_to_take, cnt_iterations))
print ("No of permutations", len(set_of_taken))

Already performed count of iterations with pairs of jigsaw permutations 100
Length of set of taken:  68
Already performed count of iterations with pairs of jigsaw permutations 200
Length of set of taken:  130
Already performed count of iterations with pairs of jigsaw permutations 300
Length of set of taken:  190
Already performed count of iterations with pairs of jigsaw permutations 400
Length of set of taken:  264
Already performed count of iterations with pairs of jigsaw permutations 500
Length of set of taken:  338
Already performed count of iterations with pairs of jigsaw permutations 600
Length of set of taken:  402
Already performed count of iterations with pairs of jigsaw permutations 700
Length of set of taken:  472
Already performed count of iterations with pairs of jigsaw permutations 800
Length of set of taken:  534
Already performed count of iterations with pairs of jigsaw permutations 900
Length of set of taken:  608
Already performed count of iterations with pairs of jigs

In [22]:
hd = hamming([3,2,1],[1,3,2])
hd

1.0

In [3]:
# Build the array for selected permutation indices above
selected_permuts = []
for ind, perm_id in enumerate(set_of_taken):
    if ind < 10:
        print ("Sample permutation {}".format(ind))
        print (permuts_array[perm_id])
    selected_permuts.append(permuts_array[perm_id])

selected_permuts = np.array(selected_permuts)
np.save('selected_permuts.npy', selected_permuts)

Sample permutation 0
[2 5 7 0 4 1 3 6 8]
Sample permutation 1
[5 3 8 1 2 0 7 4 6]
Sample permutation 2
[2 3 4 0 1 5 8 6 7]
Sample permutation 3
[0 1 7 6 2 8 5 3 4]
Sample permutation 4
[0 5 8 1 7 2 6 4 3]
Sample permutation 5
[8 1 0 2 6 7 4 3 5]
Sample permutation 6
[4 6 7 3 1 5 8 0 2]
Sample permutation 7
[1 8 6 7 4 5 2 3 0]
Sample permutation 8
[4 8 6 5 3 2 1 0 7]
Sample permutation 9
[8 4 5 6 2 1 0 3 7]
